apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Varnit01-dev/go_webapp.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  health:
    status: Healthy 